namespace Gravy.Application.Users.Queries.DeliveryPersons.GetDeliveryPersonAvailabilities;

public sealed record DeliveryPersonAvailabilityListResponse(
    IReadOnlyCollection<DeliveryPersonAvailabilityDetailsResponse> DeliveryPersonAvailabilities);
